### ISSUE TITLE
依赖注入有问题，找不到原因

### ISSUE THREAD

**Issue by GreatGodJackChen** [yang-xiaodong/eShopOnContainers#2]
An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HostedServiceExecutor (ReflectionActivator), Services = [Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IHostedService[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Hosting.IHostedService, Microsoft.Extensions.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DefaultBootstrapper (ReflectionActivator), Services = [Microsoft.Extensions.Hosting.IHostedService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IProcessingServer[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[DotNetCore.CAP.IProcessingServer, DotNetCore.CAP, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConsumerHandler (ReflectionActivator), Services = [DotNetCore.CAP.IProcessingServer], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = RabbitMQConsumerClientFactory (ReflectionActivator), Services = [DotNetCore.CAP.IConsumerClientFactory], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---&gt; An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConnectionChannelPool (ReflectionActivator), Services = [DotNetCore.CAP.RabbitMQ.IConnectionChannelPool], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---&gt; An exception was thrown while invoking the constructor &#039;Void .ctor(Microsoft.Extensions.Logging.ILogger`1[DotNetCore.CAP.RabbitMQ.ConnectionChannelPool], DotNetCore.CAP.CapOptions, DotNetCore.CAP.RabbitMQOptions)&#039; on type &#039;ConnectionChannelPool&#039;. ---&gt; Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)

**Comment by yang-xiaodong** [comment]
排版太乱，看不懂
